package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ComplaintStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintStatusAllPropertiesEquals(ComplaintStatus expected, ComplaintStatus actual) {
        assertComplaintStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertComplaintStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintStatusAllUpdatablePropertiesEquals(ComplaintStatus expected, ComplaintStatus actual) {
        assertComplaintStatusUpdatableFieldsEquals(expected, actual);
        assertComplaintStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintStatusAutoGeneratedPropertiesEquals(ComplaintStatus expected, ComplaintStatus actual) {
        assertThat(expected)
            .as("Verify ComplaintStatus auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintStatusUpdatableFieldsEquals(ComplaintStatus expected, ComplaintStatus actual) {
        assertThat(expected)
            .as("Verify ComplaintStatus relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getCreate_by()).as("check create_by").isEqualTo(actual.getCreate_by()))
            .satisfies(
                e ->
                    assertThat(e.getCreated_at())
                        .as("check created_at")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getCreated_at())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintStatusUpdatableRelationshipsEquals(ComplaintStatus expected, ComplaintStatus actual) {}
}
